extends: airbnb
parser: "babel-eslint"
env:
  es6: true
  browser: true
plugins:
  - react
  - jsx-a11y
  - import
rules:
  semi: ["error", "never"]
  no-plusplus: 0
  no-restricted-syntax: ["off", "ForInStatement"]
  max-len: 0
  newline-per-chained-call: 0
  no-undef: 1
  "no-param-reassign": [2, {"props": false}]
  no-mixed-operators: 0
  camelcase: 0
  no-console: 0
  no-underscore-dangle: 0
globals:

#  document: true
#  THREE: true
#  window: true
#  debug: true
#  THREERobot: true
#  define: true
