sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run build
  - npm run cover
after_success:
  - npm run report-coverage
  - bash <(curl -s https://codecov.io/bash)
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
